name: GitHub Actions Kubernetes
run-name: ${{ github.actor }} is deploying to Kube
on: [push]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest

    steps:
    #   - name: Build Docker images 
    #     run: | 
    #         docker build -t clairesbaffe/php-gestion-produits:1.0 ./php
    #         docker build -t clairesbaffe/mysql-gestion-produits:1.0 ./database

    #   - name: Push images to Docker Hub
    #     run: |
    #         docker push clairesbaffe/php-gestion-produits:1.0
    #         docker push clairesbaffe/mysql-gestion-produits:1.0


      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Set up kubectl
        uses: azure/setup-kubectl@v4
        with:
          version: 'latest'

      - name: Configure Kubeconfig
        run: |
          mkdir -p ~/.kube
          echo "${{ secrets.KUBE_CONFIG }}" > ~/.kube/config

      - name: Verify connection
        run: kubectl get pods --namespace claire

      - name: Deploy app
        run: |
          kubectl apply -f k8s
